export { default as TUTORIAL_IMG_ANSWER_IS_HERE } from "./TUTORIAL_IMG_ANSWER_IS_HERE.png";
export { default as TUTORIAL_IMG_CONFIRM_ANSWER } from "./TUTORIAL_IMG_CONFIRM_ANSWER.png";
export { default as TUTORIAL_IMG_ANSWER_IS_PURPLE } from "./TUTORIAL_IMG_ANSWER_IS_PURPLE.png";
